# Generated by Django 4.2.5 on 2023-10-17 07:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_age_account_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='interests',
            field=models.ManyToManyField(related_name='related_to', through='accounts.UserInterest', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='interest',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='preference_score',
            field=models.PositiveIntegerField(default=50, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='userinterest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_interests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
